from __future__ import annotations

import argparse
import csv
import json
import logging
import math
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch

import test_n100
from src.CVPSolver import SolverConfig, solve
from src.CVXPYLayerSolver import solve_ordered_targets_objective_torch, solve_ordered_targets_torch
from src.TSPEnv import generate_sequences
from src.TSPModel import ModelConfig, TSPModel
from src.TSPTester import _build_augmented_instances, _normalize_sequence_input, _resolve_max_pomo_size
from src.TSProblemDef import CVTSPInstance, RandomCVTSPGenerator, load_dataset
from src.TSPUtils import load_checkpoint, set_seed


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Compare Gurobi and cvxpylayer lower-solver objective/time on the same hard routes "
            "generated by a trained upper TSP model."
        )
    )
    parser.add_argument("--checkpoint-path", required=True, help="Path to model checkpoint .pt file.")
    parser.add_argument("--output-dir", default="outputs/lower_solver_time_compare", help="Directory for CSV/JSON logs.")
    parser.add_argument("--mode", choices=["real529", "random"], default="real529")
    parser.add_argument("--split", choices=["all", "train", "val", "test"], default="all")
    parser.add_argument("--dataset-dir", default="instance/Data")
    parser.add_argument("--max-instances", type=int, default=20, help="Limit instances for timing. Use 0 for all.")
    parser.add_argument("--problem-size", type=int, help="Only evaluate this J. Random mode uses this fixed J.")
    parser.add_argument("--random-episodes", type=int, default=20)
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument("--cuda-device", type=int, default=0)
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--decode-type", choices=["greedy", "sample"], default="greedy")
    parser.add_argument("--num-candidates", type=int, help="Override generated route candidates per rollout.")
    parser.add_argument("--sample-max-rollouts", type=int, default=32)
    parser.add_argument("--augmentation", action="store_true")
    parser.add_argument("--aug-factor", type=int, default=8)
    parser.add_argument(
        "--max-routes-per-instance",
        type=int,
        default=0,
        help="Limit route candidates after de-duplication. Use 0 for all generated routes.",
    )
    parser.add_argument("--pomo-size", type=int, default=int(test_n100.env_params.get("pomo_size", 100)))
    parser.add_argument(
        "--pomo-divisor",
        type=int,
        default=(
            int(test_n100.env_params["pomo_divisor"])
            if test_n100.env_params.get("pomo_divisor") is not None
            else None
        ),
    )
    parser.add_argument("--gurobi-threads", type=int, default=32)
    parser.add_argument("--gurobi-time-limit", type=float)
    parser.add_argument("--cvxpylayer-eps", type=float, default=1e-5)
    parser.add_argument("--cvxpylayer-max-iters", type=int, default=10000)
    parser.add_argument("--cvxpylayer-dtype", choices=["float32", "float64"], default="float64")
    parser.add_argument(
        "--cvxpylayer-output",
        choices=["objective", "full"],
        default="objective",
        help="objective is faster and matches hard-reward timing; full also returns the full CVP variables internally.",
    )
    parser.add_argument(
        "--cvxpylayer-batch-size",
        type=int,
        default=0,
        help="Chunk size for batched cvxpylayer solves. Use 0 to solve all routes for one instance in one batch.",
    )
    parser.add_argument(
        "--warmup-cvxpylayer",
        action="store_true",
        help="Build/warm the cvxpylayer once per J before recording solve time.",
    )
    parser.add_argument("--log-every", type=int, default=1)
    return parser


def _finite_or_none(value: float) -> float | None:
    return float(value) if math.isfinite(float(value)) else None


def _mean(values: list[float]) -> float | None:
    finite = [float(value) for value in values if math.isfinite(float(value))]
    if not finite:
        return None
    return float(sum(finite) / len(finite))


def _sum(values: list[float]) -> float:
    return float(sum(float(value) for value in values if math.isfinite(float(value))))


def _argmin_finite(values: list[float]) -> int | None:
    best_idx = None
    best_value = float("inf")
    for idx, value in enumerate(values):
        value = float(value)
        if math.isfinite(value) and value < best_value:
            best_idx = idx
            best_value = value
    return best_idx


def _relative_gap(candidate: float, reference: float) -> float | None:
    if not math.isfinite(candidate) or not math.isfinite(reference) or abs(reference) < 1e-12:
        return None
    return float((candidate - reference) / abs(reference))


def _build_device(args: argparse.Namespace) -> torch.device:
    use_cuda = (not args.cpu) and torch.cuda.is_available()
    if not use_cuda:
        return torch.device("cpu")
    torch.cuda.set_device(args.cuda_device)
    return torch.device("cuda", args.cuda_device)


def _build_model(args: argparse.Namespace, device: torch.device) -> TSPModel:
    env_params = dict(test_n100.env_params)
    model_params = dict(test_n100.model_params)
    env_params["dataset_dir"] = args.dataset_dir
    env_params["pomo_size"] = args.pomo_size
    env_params["pomo_divisor"] = args.pomo_divisor
    if args.problem_size is not None:
        env_params["problem_size"] = args.problem_size
        env_params["max_problem_size"] = args.problem_size

    default_model = ModelConfig()
    model_config = ModelConfig(
        node_feature_dim=int(model_params.get("node_feature_dim", default_model.node_feature_dim)),
        embedding_dim=int(model_params.get("embedding_dim", default_model.embedding_dim)),
        encoder_layer_num=int(model_params.get("encoder_layer_num", default_model.encoder_layer_num)),
        qkv_dim=int(model_params.get("qkv_dim", default_model.qkv_dim)),
        head_num=int(model_params.get("head_num", default_model.head_num)),
        logit_clipping=float(model_params.get("logit_clipping", default_model.logit_clipping)),
        ff_hidden_dim=int(model_params.get("ff_hidden_dim", default_model.ff_hidden_dim)),
        max_pomo_size=_resolve_max_pomo_size(env_params, model_params, default_model.max_pomo_size),
        pomo_divisor=args.pomo_divisor,
        start_node_strategy=str(env_params.get("start_node_strategy", default_model.start_node_strategy)),
    )

    model = TSPModel(model_config).to(device)
    load_checkpoint(args.checkpoint_path, model, map_location=device)
    model.eval()
    return model


def _load_instances(args: argparse.Namespace) -> list[CVTSPInstance]:
    if args.mode == "real529":
        instances = load_dataset(args.dataset_dir, args.split)
    else:
        generator = RandomCVTSPGenerator(
            dataset_dir=args.dataset_dir,
            min_problem_size=args.problem_size or int(test_n100.env_params.get("min_problem_size", 20)),
            max_problem_size=args.problem_size or int(test_n100.env_params.get("max_problem_size", 100)),
            problem_sizes=[args.problem_size] if args.problem_size is not None else test_n100.env_params.get("problem_sizes"),
            seed=args.seed,
        )
        instances = [generator.sample_instance(problem_size=args.problem_size) for _ in range(args.random_episodes)]

    if args.problem_size is not None:
        instances = [instance for instance in instances if instance.J == args.problem_size]
    if args.max_instances and args.max_instances > 0:
        instances = instances[: args.max_instances]
    if not instances:
        raise ValueError("No instances selected for comparison.")
    return instances


def _generate_route_candidates(
    model: TSPModel,
    instance: CVTSPInstance,
    args: argparse.Namespace,
    device: torch.device,
) -> list[list[int]]:
    source_instances = (
        _build_augmented_instances(instance, args.aug_factor)
        if args.augmentation
        else [instance]
    )
    all_sequences: list[list[int]] = []
    num_candidates = args.num_candidates if args.num_candidates is not None else model.config.max_pomo_size
    with torch.no_grad():
        for source_instance in source_instances:
            all_sequences.extend(
                generate_sequences(
                    model=model,
                    instance=source_instance,
                    device=device,
                    decode_type=args.decode_type,
                    num_candidates=num_candidates,
                    sample_max_rollouts=args.sample_max_rollouts,
                )
            )
    sequences = _normalize_sequence_input(all_sequences)
    if args.max_routes_per_instance and args.max_routes_per_instance > 0:
        sequences = sequences[: args.max_routes_per_instance]
    return sequences


def _solve_gurobi_routes(
    instance: CVTSPInstance,
    sequences: list[list[int]],
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    config = SolverConfig(
        solver_backend="gurobi",
        gurobi_time_limit=args.gurobi_time_limit,
        gurobi_threads=args.gurobi_threads,
        output_flag=0,
    )
    records = []
    for sequence in sequences:
        solution = solve(instance, sequence, config)
        records.append(
            {
                "objective": float(solution.objective),
                "time": float(solution.solve_time),
                "status": solution.status,
                "success": bool(solution.success),
            }
        )
    return records


def _solve_cvxpylayer_chunk(
    instance: CVTSPInstance,
    sequences: list[list[int]],
    args: argparse.Namespace,
) -> tuple[list[float], float, str]:
    ordered_targets = np.stack([instance.targets[sequence] for sequence in sequences], axis=0)
    solver_args = {"eps": args.cvxpylayer_eps, "max_iters": args.cvxpylayer_max_iters}
    start_time = time.perf_counter()
    with torch.no_grad():
        if args.cvxpylayer_output == "full":
            result = solve_ordered_targets_torch(
                depot=instance.depot,
                ordered_targets=ordered_targets,
                carrier_speed=instance.carrier_speed,
                uav_speed=instance.uav_speed,
                endurance=instance.endurance,
                solver_args=solver_args,
                dtype=args.cvxpylayer_dtype,
            )
            objective = result["objective"]
            status = "CVXPYLAYER_FULL_BATCH"
        else:
            objective = solve_ordered_targets_objective_torch(
                depot=instance.depot,
                ordered_targets=ordered_targets,
                carrier_speed=instance.carrier_speed,
                uav_speed=instance.uav_speed,
                endurance=instance.endurance,
                solver_args=solver_args,
                dtype=args.cvxpylayer_dtype,
            )
            status = "CVXPYLAYER_OBJECTIVE_BATCH"
    elapsed = time.perf_counter() - start_time
    values = [float(value) for value in objective.detach().cpu().reshape(-1).tolist()]
    return values, float(elapsed), status


def _solve_cvxpylayer_routes(
    instance: CVTSPInstance,
    sequences: list[list[int]],
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    if not sequences:
        return []
    batch_size = args.cvxpylayer_batch_size if args.cvxpylayer_batch_size and args.cvxpylayer_batch_size > 0 else len(sequences)
    records: list[dict[str, Any]] = []
    for start in range(0, len(sequences), batch_size):
        chunk = sequences[start : start + batch_size]
        try:
            objectives, elapsed, status = _solve_cvxpylayer_chunk(instance, chunk, args)
            per_route_time = elapsed / max(len(chunk), 1)
            records.extend(
                {
                    "objective": float(objective),
                    "time": float(per_route_time),
                    "batch_time": float(elapsed),
                    "status": status,
                    "success": bool(math.isfinite(float(objective))),
                }
                for objective in objectives
            )
        except Exception as exc:  # pragma: no cover
            per_route_time = 0.0
            records.extend(
                {
                    "objective": float("inf"),
                    "time": per_route_time,
                    "batch_time": 0.0,
                    "status": f"ERROR:{type(exc).__name__}",
                    "success": False,
                }
                for _ in chunk
            )
    return records


def _warmup_cvxpylayer(instances: list[CVTSPInstance], args: argparse.Namespace) -> float:
    if not args.warmup_cvxpylayer:
        return 0.0
    seen_sizes: set[int] = set()
    total = 0.0
    for instance in instances:
        if instance.J in seen_sizes:
            continue
        seen_sizes.add(instance.J)
        sequence = list(range(instance.J))
        _, elapsed, _ = _solve_cvxpylayer_chunk(instance, [sequence], args)
        total += elapsed
    return float(total)


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def _compare_instance(
    instance: CVTSPInstance,
    model: TSPModel,
    args: argparse.Namespace,
    device: torch.device,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    route_start = time.perf_counter()
    sequences = _generate_route_candidates(model, instance, args, device)
    route_generation_time = time.perf_counter() - route_start

    gurobi_records = _solve_gurobi_routes(instance, sequences, args)
    cvx_records = _solve_cvxpylayer_routes(instance, sequences, args)

    route_rows = []
    route_abs_diffs = []
    route_rel_diffs = []
    for idx, (sequence, gurobi, cvx) in enumerate(zip(sequences, gurobi_records, cvx_records)):
        abs_diff = (
            float(cvx["objective"] - gurobi["objective"])
            if math.isfinite(cvx["objective"]) and math.isfinite(gurobi["objective"])
            else None
        )
        rel_diff = _relative_gap(float(cvx["objective"]), float(gurobi["objective"]))
        if abs_diff is not None:
            route_abs_diffs.append(abs(abs_diff))
        if rel_diff is not None:
            route_rel_diffs.append(abs(rel_diff))
        route_rows.append(
            {
                "instance_id": instance.instance_id,
                "J": instance.J,
                "candidate_idx": idx,
                "gurobi_objective": _finite_or_none(gurobi["objective"]),
                "cvxpylayer_objective": _finite_or_none(cvx["objective"]),
                "cvx_minus_gurobi": abs_diff,
                "relative_gap": rel_diff,
                "gurobi_time_sec": gurobi["time"],
                "cvxpylayer_time_sec": cvx["time"],
                "cvxpylayer_batch_time_sec": cvx.get("batch_time", cvx["time"]),
                "gurobi_status": gurobi["status"],
                "cvxpylayer_status": cvx["status"],
                "sequence_1based": " ".join(str(node + 1) for node in sequence),
            }
        )

    gurobi_objs = [record["objective"] for record in gurobi_records]
    cvx_objs = [record["objective"] for record in cvx_records]
    best_gurobi_idx = _argmin_finite(gurobi_objs)
    best_cvx_idx = _argmin_finite(cvx_objs)
    best_gurobi_obj = gurobi_objs[best_gurobi_idx] if best_gurobi_idx is not None else float("inf")
    best_cvx_obj = cvx_objs[best_cvx_idx] if best_cvx_idx is not None else float("inf")
    cvx_on_gurobi_best = cvx_objs[best_gurobi_idx] if best_gurobi_idx is not None else float("inf")
    gurobi_on_cvx_best = gurobi_objs[best_cvx_idx] if best_cvx_idx is not None else float("inf")

    instance_summary = {
        "instance_id": instance.instance_id,
        "J": instance.J,
        "num_routes": len(sequences),
        "route_generation_time_sec": float(route_generation_time),
        "gurobi_total_time_sec": _sum([record["time"] for record in gurobi_records]),
        "cvxpylayer_total_time_sec": _sum([record["time"] for record in cvx_records]),
        "gurobi_avg_time_sec": _mean([record["time"] for record in gurobi_records]),
        "cvxpylayer_avg_time_sec": _mean([record["time"] for record in cvx_records]),
        "best_gurobi_candidate_idx": best_gurobi_idx,
        "best_cvxpylayer_candidate_idx": best_cvx_idx,
        "best_gurobi_objective": _finite_or_none(best_gurobi_obj),
        "best_cvxpylayer_objective": _finite_or_none(best_cvx_obj),
        "cvxpylayer_on_gurobi_best_objective": _finite_or_none(cvx_on_gurobi_best),
        "gurobi_on_cvxpylayer_best_objective": _finite_or_none(gurobi_on_cvx_best),
        "cvxpylayer_on_gurobi_best_gap": _relative_gap(float(cvx_on_gurobi_best), float(best_gurobi_obj)),
        "gurobi_on_cvxpylayer_best_gap": _relative_gap(float(gurobi_on_cvx_best), float(best_gurobi_obj)),
        "mean_route_abs_objective_diff": _mean(route_abs_diffs),
        "mean_route_abs_relative_gap": _mean(route_rel_diffs),
    }
    g_time = float(instance_summary["gurobi_total_time_sec"])
    c_time = float(instance_summary["cvxpylayer_total_time_sec"])
    instance_summary["solver_speedup_gurobi_over_cvxpylayer"] = g_time / c_time if c_time > 0 else None
    return route_rows, instance_summary


def main() -> None:
    args = _build_parser().parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(output_dir / "run.log", encoding="utf-8"),
        ],
    )
    logger = logging.getLogger("compare_lower_solver_time")

    set_seed(args.seed)
    device = _build_device(args)
    instances = _load_instances(args)
    model = _build_model(args, device)

    args_snapshot = vars(args).copy()
    args_snapshot["device"] = str(device)
    (output_dir / "params.json").write_text(json.dumps(args_snapshot, indent=2), encoding="utf-8")

    warmup_time = _warmup_cvxpylayer(instances, args)
    if warmup_time:
        logger.info("cvxpylayer warmup finished in %.4fs", warmup_time)

    route_rows: list[dict[str, Any]] = []
    instance_rows: list[dict[str, Any]] = []
    wall_start = time.perf_counter()
    for idx, instance in enumerate(instances, start=1):
        rows, instance_summary = _compare_instance(instance, model, args, device)
        route_rows.extend(rows)
        instance_rows.append(instance_summary)
        if idx == 1 or idx % max(args.log_every, 1) == 0 or idx == len(instances):
            logger.info(
                "%d/%d %s J=%d routes=%d gurobi=%.3fs cvxpylayer=%.3fs speedup=%s best_gurobi=%s cvx_on_best=%s",
                idx,
                len(instances),
                instance.instance_id,
                instance.J,
                instance_summary["num_routes"],
                instance_summary["gurobi_total_time_sec"],
                instance_summary["cvxpylayer_total_time_sec"],
                (
                    f"{instance_summary['solver_speedup_gurobi_over_cvxpylayer']:.2f}x"
                    if instance_summary["solver_speedup_gurobi_over_cvxpylayer"] is not None
                    else "NA"
                ),
                instance_summary["best_gurobi_objective"],
                instance_summary["cvxpylayer_on_gurobi_best_objective"],
            )

    wall_time = time.perf_counter() - wall_start
    _write_csv(output_dir / "route_compare.csv", route_rows)
    _write_csv(output_dir / "instance_summary.csv", instance_rows)

    total_gurobi_time = _sum([row["gurobi_time_sec"] for row in route_rows])
    total_cvx_time = _sum([row["cvxpylayer_time_sec"] for row in route_rows])

    route_abs_gaps = [
        abs(float(row["relative_gap"]))
        for row in route_rows
        if row["relative_gap"] is not None and math.isfinite(float(row["relative_gap"]))
    ]
    summary = {
        "num_instances": len(instances),
        "num_routes": len(route_rows),
        "wall_time_sec": float(wall_time),
        "cvxpylayer_warmup_time_sec": float(warmup_time),
        "route_generation_time_sec": _sum([row["route_generation_time_sec"] for row in instance_rows]),
        "gurobi_total_time_sec": float(total_gurobi_time),
        "cvxpylayer_total_time_sec": float(total_cvx_time),
        "solver_speedup_gurobi_over_cvxpylayer": (
            float(total_gurobi_time / total_cvx_time) if total_cvx_time > 0 else None
        ),
        "avg_best_gurobi_objective": _mean([row["best_gurobi_objective"] for row in instance_rows if row["best_gurobi_objective"] is not None]),
        "avg_cvxpylayer_on_gurobi_best_objective": _mean(
            [row["cvxpylayer_on_gurobi_best_objective"] for row in instance_rows if row["cvxpylayer_on_gurobi_best_objective"] is not None]
        ),
        "mean_route_abs_relative_gap": _mean(route_abs_gaps),
        "config": args_snapshot,
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    logger.info("Summary: %s", json.dumps(summary, ensure_ascii=True))


if __name__ == "__main__":
    main()
